name: test

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Run date on ubuntu
        run: date
  job2:
    runs-on: windows-latest
    steps:
      - name: Run date on windows
        run: Get-Date
  job3:
    runs-on: macos-latest
    steps:
      - name: Run date on macos
        run: date

  job4:
    runs-on: ubuntu-18.04
    needs: [job1, job2, job3]
    steps:
      - name: Run date on ubuntu 18.04
        run: date
